### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by mrpandey** [ssloy/tinykaboom#1]
Even though WTFPL is mentioned in readme, I think it is pretty standard to add a license text file. Most GitHub users look for license information in the bar at the top, which is detected from the license text file.

BTW thank you for creating all these wonderful projects on OpenGL.

**Comment by ssloy** [comment]
I respectfully disagree. First, github does not recognize licenses besides a handful of chosen ones. <a href="https://github.com/ssloy/tinyrenderer">Here is an example</a>, as you can see, no top bar indicators. Next, a separate file would pollute this **tiny** project. Last, but not least, I do not think this project would be used by anyone as is, and thus spreading the licensing plague is not a good idea.

**Comment by mrpandey** [comment]
Thank you for quick reply. It is interesting to see that GitHub doesn't recognize all licenses. I respect your viewpoint. So, I will leave the matter closed.
