### ISSUE TITLE
Incorrect description/link in the about section

### ISSUE THREAD

**Issue by QH4OS** [ssloy/tinykaboom#3]
I think you may have used the one for your OpenGL renderer instead of the one for tinykaboom

**Comment by ssloy** [comment]
which one is it? i do not see the faulty link

**Comment by QH4OS** [comment]
![kaboom](https://user-images.githubusercontent.com/69046613/92772876-1acdcf80-f36a-11ea-819d-3e326319f0b1.jpg)

**Comment by ssloy** [comment]
Nice catch, thank you! Fixed.
